# Generated by Django 5.2.5 on 2025-10-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('types', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_offers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
