# Generated by Django 5.2.5 on 2026-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
